END_GOBLIN_ALT_TEXTURE = false
GENERATE_OPAL_ORE = true
END_GOBLIN_CAN_SPAWN_IN_END = true
END_GOBLIN_CAN_SPAWN_IN_OVERWORLD = true
END_GOBLIN_CAN_SPAWN_IN_HELL = true
END_GOBLIN_SPAWN_RATE = 35
END_GOBLIN_SPAWN_RATE_D = 1
END_GOBLIN_GROUP_SIZE = 2
END_GOBLIN_SPAWN_RATE_OVERWORLD = 15
END_GOBLIN_GROUP_SIZE_OVERWORLD = 2
END_GOBLIN_SPAWN_RATE_HELL = 15
END_GOBLIN_GROUP_SIZE_HELL = 2
D = true
